# this docker-compose.yml file only serves as an example
# of how the flowofcontrol/docker-kafka can be used and
# set up together with flowofcontrol/docker-zookeeper in
# a docker-compose
version: '2.1'

services:
  zookeeper:
    image: flowofcontrol/docker-zookeeper
  kafka:
    image: flowofcontrol/docker-kafka
    depends_on:
      - zookeeper
    volumes:
      - ./config:/kafka-config
    links:
      - zookeeper:zookeeper
